from app.db.base_class import Base
from app.models.asset_register import AssetRegisterItem
from app.models.behaviour_observation import BehaviourObservation
from app.models.attachment import Attachment
from app.models.audit_management import AuditManagementRecord
from app.models.audit_log import AuditLog
from app.models.contractor import ContractorRecord
from app.models.corrective_action import (
    ActionActivity,
    ActionAssignmentHistory,
    ActionComment,
    ActionContributor,
    ActionExtensionRequest,
    ActionReferenceSequence,
    ActionReminderDelivery,
    ActionTask,
    CorrectiveAction,
)
from app.models.data_import import DataImportJob, DataImportRow
from app.models.department import Department
from app.models.document_control import DocumentControlRecord
from app.models.emergency_drill import EmergencyDrillRecord
from app.models.hazard import Hazard
from app.models.incident import (
    Incident,
    IncidentActivity,
    IncidentCauseAnalysis,
    IncidentCauseCategory,
    IncidentClassification,
    IncidentClosureHistory,
    IncidentEnvironmentalDetail,
    IncidentEvent,
    IncidentFinding,
    IncidentInjury,
    IncidentLink,
    IncidentPerson,
    IncidentPropertyDamage,
    IncidentReferenceSequence,
    IncidentRegulatoryNotification,
    IncidentReminderDelivery,
    IncidentReturnToWork,
    IncidentTreatment,
    IncidentVehicleDetail,
    IncidentWitnessStatement,
)
from app.models.incident_investigation import IncidentInvestigation
from app.models.inspection import Inspection
from app.models.jsa import JobSafetyAnalysis
from app.models.job_run import JobRun
from app.models.legal_compliance import LegalComplianceItem
from app.models.medical_surveillance import (
    ClinicEncounter,
    FitnessCertificate,
    MedicalAppointment,
    MedicalAssessment,
    MedicalProvider,
    MedicalReminderDelivery,
    MedicalSurveillanceRecord,
    OccupationalExposureType,
    OccupationalIllnessCase,
    SurveillanceProgramme,
    SurveillanceRequirement,
    WorkerExposureAssignment,
    WorkRestriction,
)
from app.models.notification import Notification
from app.models.notification_delivery import NotificationDeliveryLog
from app.models.organisation import Organisation, OrganisationFeature, OrganisationSettings
from app.models.permit import PermitToWork
from app.models.role import Role
from app.models.safety_communication import SafetyCommunication
from app.models.safety_kpi import SafetyKPIRecord
from app.models.site import Site
from app.models.sio import (
    SIOActivity,
    SIOComment,
    SIOReferenceSequence,
    SafetyImprovementObservation,
)
from app.models.training import (
    Competency,
    CompetencyAward,
    CompetencyStatusEvent,
    ComplianceAcknowledgement,
    ContractorWorker,
    CourseCompetencyMapping,
    TrainingAssessment,
    TrainingAssignment,
    TrainingAttendance,
    TrainingCertificate,
    TrainingCourse,
    TrainingDeficiencyLink,
    TrainingRecord,
    TrainingReminderDelivery,
    TrainingRequest,
    TrainingRequirement,
    TrainingSession,
    WorkAuthorization,
)
from app.models.user import User
from app.models.ppe import (
    PPEAsset,
    PPECategory,
    PPEInspection,
    PPEInventory,
    PPEIssue,
    PPEItem,
    PPELossDamageReport,
    PPEReminderDelivery,
    PPERequest,
    PPERequirement,
    PPEReturn,
    PPEStockLocation,
    PPEStockMovement,
    PPEVariant,
)
from app.models.reporting import (
    KPIDefinition,
    KPISnapshot,
    KPITarget,
    ManagementActionPlanItem,
    OrganisationKPISetting,
    ReportExport,
    ReportSection,
    ReportingPeriod,
    ReportingPeriodHistory,
    WorkforceExposure,
)

__all__ = [
    "AssetRegisterItem",
    "BehaviourObservation",
    "Attachment",
    "AuditManagementRecord",
    "AuditLog",
    "Base",
    "ContractorRecord",
    "CorrectiveAction",
    "ActionActivity",
    "ActionAssignmentHistory",
    "ActionComment",
    "ActionContributor",
    "ActionExtensionRequest",
    "ActionReferenceSequence",
    "ActionReminderDelivery",
    "ActionTask",
    "DataImportJob",
    "DataImportRow",
    "Department",
    "DocumentControlRecord",
    "EmergencyDrillRecord",
    "Hazard",
    "Incident",
    "IncidentActivity",
    "IncidentCauseAnalysis",
    "IncidentCauseCategory",
    "IncidentClassification",
    "IncidentClosureHistory",
    "IncidentEnvironmentalDetail",
    "IncidentEvent",
    "IncidentFinding",
    "IncidentInjury",
    "IncidentLink",
    "IncidentPerson",
    "IncidentPropertyDamage",
    "IncidentReferenceSequence",
    "IncidentRegulatoryNotification",
    "IncidentReminderDelivery",
    "IncidentReturnToWork",
    "IncidentTreatment",
    "IncidentVehicleDetail",
    "IncidentWitnessStatement",
    "IncidentInvestigation",
    "Inspection",
    "JobSafetyAnalysis",
    "JobRun",
    "LegalComplianceItem",
    "MedicalSurveillanceRecord",
    "SurveillanceProgramme",
    "SurveillanceRequirement",
    "OccupationalExposureType",
    "WorkerExposureAssignment",
    "MedicalProvider",
    "MedicalAppointment",
    "MedicalAssessment",
    "FitnessCertificate",
    "WorkRestriction",
    "OccupationalIllnessCase",
    "ClinicEncounter",
    "MedicalReminderDelivery",
    "Notification",
    "NotificationDeliveryLog",
    "Organisation",
    "OrganisationFeature",
    "OrganisationSettings",
    "PermitToWork",
    "Role",
    "SafetyCommunication",
    "SafetyKPIRecord",
    "Site",
    "SafetyImprovementObservation",
    "SIOActivity",
    "SIOComment",
    "SIOReferenceSequence",
    "ComplianceAcknowledgement",
    "TrainingRecord",
    "Competency",
    "CompetencyAward",
    "CompetencyStatusEvent",
    "ContractorWorker",
    "CourseCompetencyMapping",
    "TrainingAssessment",
    "TrainingAssignment",
    "TrainingAttendance",
    "TrainingCertificate",
    "TrainingCourse",
    "TrainingDeficiencyLink",
    "TrainingReminderDelivery",
    "TrainingRequest",
    "TrainingRequirement",
    "TrainingSession",
    "WorkAuthorization",
    "User",
    "PPEAsset",
    "PPECategory",
    "PPEInspection",
    "PPEInventory",
    "PPEIssue",
    "PPEItem",
    "PPELossDamageReport",
    "PPEReminderDelivery",
    "PPERequest",
    "PPERequirement",
    "PPEReturn",
    "PPEStockLocation",
    "PPEStockMovement",
    "PPEVariant",
    "KPIDefinition",
    "KPISnapshot",
    "KPITarget",
    "ManagementActionPlanItem",
    "OrganisationKPISetting",
    "ReportExport",
    "ReportSection",
    "ReportingPeriod",
    "ReportingPeriodHistory",
    "WorkforceExposure",
]
